@echo off
echo Starting Social Media Content Analyzer...
echo.
echo Starting backend server on port 5000...
start "Backend Server" cmd /k "cd server && npm start"
echo.
echo Starting frontend server on port 3000...
start "Frontend Server" cmd /k "cd client && npm start"
echo.
echo Both servers are starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000
echo.
echo Press any key to close this window...
pause >nul
